-- Insert FAQs for order placement guidance
INSERT INTO public.faqs (question, response) VALUES 
('How can I place an order for a MotoRise scooter?', 'You can place an order through our website at www.motorise.com, visit any of our showrooms, or call our sales team. Online orders require a 20% advance payment, with the balance due on delivery. Our sales team will guide you through model selection and delivery options.'),
('What payment methods do you accept for orders?', 'We accept multiple payment methods: credit/debit cards, UPI, net banking, cash (for showroom purchases), and EMI options. For online orders, we require 20% advance payment. EMI plans are available with 0% interest for up to 12 months through our partner banks.'),
('What documents do I need to place an order?', 'For placing an order, you need: valid photo ID (Aadhaar/PAN/Driving License), address proof, and phone number for delivery coordination. For EMI purchases, additional income proof may be required. All documents can be uploaded during online checkout.'),
('How long does delivery take after placing an order?', 'Standard delivery takes 5-7 business days within major cities and 7-10 days for other locations. Express delivery (available in select cities) takes 2-3 days with additional charges. We provide real-time tracking once your order is dispatched.'),
('Can I customize my scooter order?', 'Yes! You can choose from available colors, add accessories like phone holders, additional battery packs, or premium seat covers. Customization options are shown during the ordering process. Some customizations may add 2-3 days to delivery time.'),
('What is included with my scooter order?', 'Every MotoRise scooter order includes: the scooter, charger, user manual, toolkit, helmet (complimentary), 24-month warranty, and free home delivery. Registration assistance is provided in select cities. Insurance can be added during checkout.'),
('Can I cancel or modify my order?', 'Orders can be cancelled or modified within 24 hours of placement. After production begins, only color changes may be possible. Cancelled orders receive full refund within 5-7 business days. Contact our sales team immediately for any changes.'),
('Do you offer test rides before ordering?', 'Yes! Test rides are available at all our showrooms and select partner dealers. You can also book a home test ride in major cities (small fee applies, adjusted against order if you purchase). Book test rides through our website or call customer care.'),
('Are there any offers or discounts available?', 'We regularly offer seasonal discounts, exchange offers for old vehicles, student discounts, and corporate bulk discounts. Current offers are displayed on our website and communicated by our sales team. Subscribe to our newsletter for exclusive deals.'),
('What areas do you deliver to?', 'We deliver pan-India to all major cities and towns. Remote area delivery may take additional 3-5 days with possible extra charges. Check delivery availability for your pincode during checkout or contact our sales team for confirmation.');