// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpaanzkehlyigifceanr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wYWFuemtlaGx5aWdpZmNlYW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjE3MzksImV4cCI6MjA2ODQ5NzczOX0.e3CqFwO0q-Kkwr7AzFnbGX1Kr81547hcZ8LtnBYgaQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});